# Generated by Django 4.2.3 on 2023-07-26 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.UUIDField(auto_created=True, primary_key=True, serialize=False)),
                ('user_type', models.IntegerField(choices=[('0', 'CUSTOMER'), ('1', 'BUSINESS')])),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('event_id', models.UUIDField(auto_created=True, primary_key=True, serialize=False)),
                ('location', models.CharField(max_length=255)),
                ('event_name', models.CharField(max_length=255)),
                ('event_description', models.CharField(max_length=255)),
                ('event_summary', models.CharField(max_length=255)),
                ('attendees', models.ManyToManyField(related_name='events_attending', to='api.user')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=255)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
        ),
    ]
