# Generated by Django 4.2.3 on 2023-07-05 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.UUIDField(auto_created=True, primary_key=True, serialize=False)),
            ],
        ),
    ]
