# Generated by Django 4.2.3 on 2023-07-05 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detty_server', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('comment_id', models.UUIDField(auto_created=True, primary_key=True, serialize=False)),
                ('comment', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('event_id', models.UUIDField(auto_created=True, primary_key=True, serialize=False)),
                ('location', models.CharField(max_length=255)),
                ('event_name', models.CharField(max_length=255)),
                ('event_description', models.CharField(max_length=255)),
                ('event_summary', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.IntegerField(choices=[('0', 'CUSTOMER'), ('1', 'BUSINESS')], default=0),
            preserve_default=False,
        ),
    ]
